name: publish
on:
  push:
    branches:
      - main
    tags:
      - v**
jobs:
  pypi-publish:
    name: Upload to PyPI
    environment: release
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install tools
        run: pip install poetry
      - name: Build the release packages
        run: |
          poetry build
          sha256sum dist/*

      # only publish tagged commits to PyPI
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
